### ISSUE TITLE
Link here from archived project?

### ISSUE THREAD

**Issue by fredwilby** [vifreefly/kimuraframework#10]
Hi, thanks for your work on this project, it's really nice to work with. One thing that keeps bothering me is that when you google 'kimurai' the top result is [this](https://github.com/vfreefly/kimurai) archived project. Not sure why that happened, but it's probably a good idea to link here from there so people don't think the project is dead.

**Comment by caecity43** [comment]
@fredwilby Because of the archived project DMCA issues.

**Comment by lewstherin** [comment]
+1
I was very disappointed at first when I saw it, but luckily discovered your reddit post on the same. Thank you for the great work.
