### ISSUE TITLE
when use selenium Docker, how to set remote url ?

### ISSUE THREAD

**Issue by tianlu1677** [vifreefly/kimuraframework#12]
when use kimura,  so how to controller remote selenium chrome ?

**Comment by vifreefly** [comment]
@tianlu1677 It is unsupported for now, but it is a good idea to add this feature

**Comment by tianlu1677** [comment]
Thanks. Install chrome driver is a litter hard for newbie , for example me . Use docker is easier.

**Comment by vifreefly** [comment]
@tianlu1677 There are docs https://github.com/vifreefly/kimuraframework#installation , you can install chromedriver within 3 commands on Ubuntu, and within 1 command on Mac OS X.

**Comment by tianlu1677** [comment]
Thanks. I install manual operation, it is good.
 
when I use ansible, it has some errors. I don't use ansible before, I do not know what is that meaning.
```
☁  ~  ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg

  configured module search path = Default w/o overrides
Using /home/deploy/.rvm/gems/ruby-2.5.1
☁  ~  kimurai setup localhost --local
ERROR! no action detected in task

The error appears to have been in '/home/deploy/.rvm/gems/ruby-2.5.1/gems/kimurai-1.2.0/lib/kimurai/automation/setup.yml': line 35, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - import_tasks: setup/ruby_environment.yml
      ^ here
```

**Comment by vifreefly** [comment]
@tianlu1677 
What is your Linux system? Ansible auto installation has an experimental status and supported OS is Ubuntu 18.04 only. 

I think you have old Ansible package version. Try with 2.5 (Ubuntu 18.04 has `2.5.1` Ansible version in the repositories).

**Comment by vifreefly** [comment]
Closed as I assume that problem is solved.
