### ISSUE TITLE
uninitialized constant Downloader::MovieEnum

### ISSUE THREAD

**Issue by caecity43** [vifreefly/kimuraframework#2]
I created `movie_enum.rb` in `./lib/`

It not loaded when I start `bundle exec kimurai crawl movie_spider`

So, I add code to `config/initializers/boot.rb` under the `require pipelines`

```
# require lib
Dir.glob(File.join("./lib", "*.rb"), &method(:require))
```

it works.

**Comment by vifreefly** [comment]
Hello @caecity43  ! 

Yes, any files under `lib/` folder should be manually required in `config/boot.rb` file. Looks like problem is solved, right? So I closing this issue.

**Comment by caecity43** [comment]
@vifreefly yes, problem is solved. :)
