### ISSUE TITLE
How to set encoding?

### ISSUE THREAD

**Issue by dccmmtop** [vifreefly/kimuraframework#20]
When the website is encoding with GB2312, the content of the website can not be obtained normally.

I think it would be better to change 
```ruby
    def current_response(response_type = :html)
      case response_type
      when :html
        Nokogiri::HTML(body)
      when :json
        JSON.parse(body)
      end
    end
```
**TO**

```ruby
    def current_response(response_type = :html)
      case response_type
      when :html
        Nokogiri::HTML(body,nil,@config[:encoding])
      when :json
        JSON.parse(body)
      end
    end

```
**OR**

```ruby
    def current_response(response_type = :html)
      case response_type
      when :html
        Nokogiri::HTML(body.force_encoding("encoding"))
      when :json
        JSON.parse(body)
      end
    end

```

**Comment by vifreefly** [comment]
@dccmmtop, I added config option `encoding`. It's in the master now: https://github.com/vifreefly/kimuraframework/commit/96fe695fe4cbcf1182389e2f867debeca746022d . 

Can you please check both cases, `:auto` and custom encoding?  

```ruby
@config = {
  encoding: nil      # do not handle encoding at all (current behavior)
  encoding: :auto    # Try to handle encoding automatically
  encoding: "GB2312" # Set required encoding manually
}
```

To use Kimurai version from master, add it to Gemfile this way:

```
gem 'kimurai', git: 'https://github.com/vifreefly/kimuraframework'
```

**Comment by dccmmtop** [comment]
I've tested the `:auto` and custom encoding and found no errors.
`:auto` is a good method, and it works in most cases. But some pages are actually coded differently from the way they are declared in the `head`.

For example, the following situation, only in the way of GBK, can I get the right content, I think this is the fault of website developers.
![image](https://user-images.githubusercontent.com/17303988/51423761-bba0d180-1bff-11e9-80f0-f4c6a5e8fee7.png)

**Comment by dccmmtop** [comment]
@vifreefly Sorry to have misunderstood you.

`：auto` has no errors and can work normally.
What I mean is that the actual encoding of a web page is different from what it declares in <meta charset='encoding'>.

**Comment by vifreefly** [comment]
@dccmmtop 
Thanks, now I see what you've meant :)

**Comment by dccmmtop** [comment]
The same website has different coding methods， but the `@config` is global。

Should you specify a separate encoding for a url?
example:
```ruby
request_to(:parse_content, url: link, encoding: 'GBK')
```

Now that's how I solve it.
```ruby
    @config = {
      before_request: { delay: 1..3 },
      encoding: 'utf-8'
    }

    def parse(response,url:,data:{})
      topics = JSON.parse(response.xpath("//p").text[/(\[.+\])/,1])
      topics.each do |topic|
        link = topic["url"].strip
        self.class.config[:encoding] = "GBK"
        request_to(:parse_content, url: link)
        self.class.config[:encoding] = "utf=8"
      end
    end

```

**Comment by vifreefly** [comment]
Thanks, I'll add this feature to the ToDo list for a new version
