### ISSUE TITLE
NoMethodError: undefined method `xpath' for :selenium_chrome:Symbol

### ISSUE THREAD

**Issue by leiz-me** [vifreefly/kimuraframework#21]
I followed the steps to run the kimurai console, but it showed me this.
And I check the @engine in the console, it went to ':mechanize'.

What did I miss ?

**Comment by zousu** [comment]
Because url is nil, response is symbol ":selenium_chrome"
I tried [browser object](https://github.com/vifreefly/kimuraframework#browser-object) and it works

![wx20190130-221013](https://user-images.githubusercontent.com/1424959/51986725-db77a580-24db-11e9-8db5-b825fc4d60c7.png)

**Comment by leiz-me** [comment]
So that means THE console is not working correctly as the README described?

**Comment by Harakiri24** [comment]
Got exactly the same error. Followed instructions 1:1.

**Comment by vifreefly** [comment]
@leiz-me  Thanks for the report! There was a bug, fixed in new 1.4.0 version (https://github.com/vifreefly/kimuraframework/blob/master/CHANGELOG.md#140)

Update `gem update kimurai`, make sure that you have latest version: `kimurai -v` (should return 1.4.0) and try to test console again.

**Comment by leiz-me** [comment]
@vifreefly Thanks for your update. Confirmed it is fixed and worked as expected.
