### ISSUE TITLE
How to handle Net::HTTPNotFound error?

### ISSUE THREAD

**Issue by caecity43** [vifreefly/kimuraframework#3]
```bash
bundle exec kimurai console xxx_spider --url https://www.xxx.com/100
```

> RuntimeError: Received the following error for a GET request to https://www.xxx.com/100: '404 => Net::HTTPNotFound for https://www.xxx.com/100 -- unhandled response'

Like this log, How can I handle this?

**Comment by vifreefly** [comment]
@caecity43  You can automatically retry any failed requests (which can happen while `visit`ing some url) by providing `retry_request_errors:` option with errors which you want to retry:

```
@config = {
  browser: {
    retry_request_errors: [Net::HTTPNotFound]
  }
}
```

Keep in mind that some engines (for example mechanize) can raise StandardError. In this case add it to retry_request_errors: `retry_request_errors: [StandardError]`. With it, any errors raised while requesting a page (`request_to`) will be automatically retried (by default there is 3 retries). If after 3 retries there is still an error, then exception will be raised. If you want to handle it, use standard Ruby's `begin rescue` block:

```ruby
begin
rescue => e
```

**Comment by caecity43** [comment]
@vifreefly Thanks, It works.
