### ISSUE TITLE
How to download files in parallel?

### ISSUE THREAD

**Issue by caecity43** [vifreefly/kimuraframework#4]
I use in_parallel method to request page, but download file is not support in pipelines.

Is there any good advice? 

Thank you.

**Comment by vifreefly** [comment]
in_parallel is for web pages. If you want to download files in parallel use peach https://github.com/bruceadams/pmap + Down https://github.com/janko-m/down . 

```
array_of_files_urls.peach(10) do |url|
  Down.download(url)
end
```

**Comment by caecity43** [comment]
@vifreefly Thank you, You made my day. 😉

**Comment by vifreefly** [comment]
@caecity43  No problem :)
