### ISSUE TITLE
How to make the spider running as daemon?

### ISSUE THREAD

**Issue by caecity43** [vifreefly/kimuraframework#5]
I running spider by command:

```bash
KIMURAI_ENV=production bundle exec kimurai crawl movie_spider
```

Then close the terminal, spider will stopped.

**Comment by vifreefly** [comment]
@caecity43 
I think you need Tmux here. Or use cron https://github.com/vifreefly/kimuraframework#schedule-spiders-using-cron if you want to run the spider by schedule.

**Comment by caecity43** [comment]
@vifreefly Thank you, Let me try it.
