### ISSUE TITLE
How to set exception_on_fail option on Project mode?

### ISSUE THREAD

**Issue by caecity43** [vifreefly/kimuraframework#6]
I saw the changelog of version 1.2.0, Add `exception_on_fail` option to `Base.crawl!`

How to set this option on Project mode? 

Thanks.

**Comment by vifreefly** [comment]
@caecity43  It's not supported for now. Why do you need it?

**Comment by caecity43** [comment]
@vifreefly My project is running on project mode, I need this option to skip exception(like Down::ConnectionError).

but I found the `skip_request_errors` in config, I will try it later.

**Comment by vifreefly** [comment]
exception_on_fail is for different things. You can handle any request errors using https://github.com/vifreefly/kimuraframework#handle-request-errors or any other errors using standard Ruby's `begin rescue end` block

**Comment by caecity43** [comment]
OK, Thanks.
